apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging
  labels:
    app: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: staging
  template:
    metadata:
      labels:
        app: staging
    spec:
      containers:
        - name: staging
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "64m"
              memory: "64Mi"
            limits:
              cpu: "128m"
              memory: "128Mi"